import { createSlice } from '@reduxjs/toolkit'
import React, { act } from 'react'
import { fetchMovieAction, fetchMovieActionPopular, searchMovieAction } from './productsAction'

export const productsSlice= createSlice ({
  name:'movie',
  initialState:{
    movies:[],
    status:'idle',
    error:null
  },
  reducers:{},
  // extraReducers are for handling actions generated by createAsyncThunk
  extraReducers(builder){
    builder.addCase(searchMovieAction.pending,(state)=>{
      state.status='loading search'
    }).addCase(searchMovieAction.fulfilled,(state,action)=>{
      state.fulfilled='fullfiled'
      console.log('action.payload',action.payload)
      state.movies=action.payload
    }).addCase(searchMovieAction.rejected,(state,action)=>{
      state.status='search not found'
      state.error=action.error.message
    }).addCase(fetchMovieAction.pending,(state)=>{
      state.status='loading pending'
    }).addCase(fetchMovieAction.fulfilled,(state,action)=>{
      state.fulfilled='fullfiled'
      console.log('fectmovieactionpayload',action.payload)
      state.movies = [...state.movies, ...action.payload];
    }).addCase(fetchMovieAction.rejected,(state,action)=>{
      state.status='not found'
      state.error=action.error.message
    })
  }
})
export default productsSlice.reducer