
import React, { act } from 'react'
import { fetchMovieAction, Nowplayingfetch, searchMovieAction, TopRatefetch} from './productsAction'
import { createSlice } from '@reduxjs/toolkit'

export const productsSlice= createSlice({
  name:'movie',
  initialState:{
    movies:[],
    status:'idle',
    error:null
  },
  reducers:{},
  // reducers: {
  //   clearResults: (state) => {
  //     state.results = [];
  //   },
  // },
  // extraReducers are for handling actions generated by createAsyncThunk
  extraReducers(builder){
    builder.addCase(searchMovieAction.pending,(state)=>{
      state.status='loading search'
    }).addCase(searchMovieAction.fulfilled,(state,action)=>{
      state.fulfilled='fullfiled'
      console.log('action.payload',action.payload)
      state.movies =action.payload
                
      // state.movies=action.payload
    }).addCase(searchMovieAction.rejected,(state,action)=>{
      state.status='search not found'
      state.error=action.error.message
    })
    .addCase(fetchMovieAction.pending,(state)=>{
      state.status='loading fetch'
    }).addCase(fetchMovieAction.fulfilled,(state,action)=>{
      state.fulfilled='fullfiled'
      console.log('fectmovieactionpayload',action.payload)
      state.movies = [...state.movies, ...action.payload];
    }).addCase(fetchMovieAction.rejected,(state,action)=>{
      state.status=' fetch not found'
      state.error=action.error.message
    })
    // .addCase(Nowplayingfetch.pending,(state)=>{
    //   state.status='loading nowplaying'
    // }).addCase(Nowplayingfetch.fulfilled,(state,action)=>{
    //   state.fulfilled='fullfiled'
    //   console.log('now playing payload',action.payload)
    //   state.movies = [...state.movies, ...action.payload];
    // }).addCase(Nowplayingfetch.rejected,(state,action)=>{
    //   state.status='now playing not found'
    //   state.error=action.error.message
    // })
    // .addCase(TopRatefetch.pending,(state)=>{
    //   state.status='loading TopRating'
    // }).addCase(TopRatefetch.fulfilled,(state,action)=>{
    //   state.fulfilled='fullfiled'
    //   console.log('TopRate payload',action.payload)
    //   state.movies = [...state.movies, ...action.payload];
    // }).addCase(TopRatefetch.rejected,(state,action)=>{
    //   state.status='TopRate not found'
    //   state.error=action.error.message
    // })
  }
})
export default productsSlice.reducer;
export const { clearResults } = productsSlice.actions;
